name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AdamJeddy
          template: classic
          base: header, activity, community
          #, repositories, topics, metadata
          config_timezone: Asia/Dubai
          
          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          plugin_activity: no
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Edit this when you get more active
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: no
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_analysis_timeout: 60
          # plugin_languages_ignored: Jupyter Notebook
          plugin_languages_categories: programming
          plugin_languages_colors: rainbow
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_topics: no
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          plugin_stars: no
          plugin_stars_limit: 3
